In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import statsmodels.api as sm
import seaborn as sns

/usr/local/lib/python3.7/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm


In [2]:
df=pd.read_csv("/content/healthcare-dataset-stroke-data.csv")
df.drop(['id'],axis=1,inplace=True)
df=df.fillna(df.mean())

In [3]:
df=pd.get_dummies(df)

In [4]:
df.corr()

age  ...  smoking_status_smokes
age                             1.000000  ...               0.073133
hypertension                    0.276398  ...               0.031240
heart_disease                   0.263796  ...               0.044049
avg_glucose_level               0.238171  ...               0.017646
bmi                             0.325942  ...               0.085579
stroke                          0.245257  ...               0.008939
gender_Female                   0.027924  ...              -0.011306
gender_Male                    -0.027623  ...               0.011477
gender_Other                   -0.010659  ...              -0.005978
ever_married_No                -0.679125  ...              -0.105226
ever_married_Yes                0.679125  ...               0.105226
work_type_Govt_job              0.130013  ...               0.030026
work_type_Never_worked         -0.078653  ...              -0.028099
work_type_Private               0.116534  ...               0.100025
work_type_Self-employed         0.327989  ...              -0.003626
work_type_children             -0.634215  ...              -0.165234
Residence_type_Rural           -0.014180  ...              -0.027266
Residence_type_Urban            0.014180  ...               0.027266
smoking_status_Unknown         -0.378231  ...              -0.281177
smoking_status_formerly smoked  0.236897  ...              -0.195571
smoking_status_never smoked     0.119307  ...              -0.327653
smoking_status_smokes           0.073133  ...               1.000000

[22 rows x 22 columns]

In [5]:
X = df.drop('stroke', axis='columns')
y = df['stroke']

In [6]:
# Checking for class Imbalance
class_percentages = (df['stroke'].value_counts() / df['stroke'].value_counts().sum())*100
print(class_percentages)

0    95.127202
1     4.872798
Name: stroke, dtype: float64


In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42,stratify=y)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((3577, 21), (1533, 21), (3577,), (1533,))

In [8]:
from imblearn.over_sampling import SMOTE
sm = SMOTE(random_state=42)
X_train, y_train = sm.fit_resample(X_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function safe_indexing is deprecated; safe_indexing is deprecated in version 0.22 and will be removed in version 0.24.
  warnings.warn(msg, category=FutureWarning)


In [14]:
from sklearn.linear_model import LogisticRegression
log = LogisticRegression()                               
log.fit(X_train,y_train)
log_y_pred=log.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
cm_log=confusion_matrix(y_test,log_y_pred)
print(cm_log)
ac_log=accuracy_score(y_test,log_y_pred)
print(ac_log)
print(classification_report(y_test,log_y_pred))

from sklearn.metrics import mean_absolute_error
mae_log = mean_absolute_error(y_test,log_y_pred)*100
print(mae_log)

[[1065  393]
 [  16   59]]
0.7332028701891715
              precision    recall  f1-score   support

           0       0.99      0.73      0.84      1458
           1       0.13      0.79      0.22        75

    accuracy                           0.73      1533
   macro avg       0.56      0.76      0.53      1533
weighted avg       0.94      0.73      0.81      1533

26.679712981082844


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


In [9]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=150,criterion= 'entropy', random_state=42)                               
model.fit(X_train,y_train)
y_pred=model.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
cm_rfs=confusion_matrix(y_test,y_pred)
print(cm_rfs)
ac_rfs=accuracy_score(y_test,y_pred)
print(ac_rfs)
print(classification_report(y_test,y_pred))

from sklearn.metrics import mean_absolute_error
mape = mean_absolute_error(y_test,y_pred)*100
print(mape)

[[1448   10]
 [  72    3]]
0.9465101108936725
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      1458
           1       0.23      0.04      0.07        75

    accuracy                           0.95      1533
   macro avg       0.59      0.52      0.52      1533
weighted avg       0.92      0.95      0.93      1533

5.348988910632746


In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier()
knn.fit(X_train,y_train)
y_pred_knn=knn.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
cm_knn=confusion_matrix(y_test,y_pred_knn)
print(cm_knn)
ac_knn=accuracy_score(y_test,y_pred_knn)
print(ac_knn)
print(classification_report(y_test,y_pred_knn))

from sklearn.metrics import mean_absolute_error
mape_knn = mean_absolute_error(y_test,y_pred_knn)*100
print(mape_knn)

[[1182  276]
 [  32   43]]
0.7990867579908676
              precision    recall  f1-score   support

           0       0.97      0.81      0.88      1458
           1       0.13      0.57      0.22        75

    accuracy                           0.80      1533
   macro avg       0.55      0.69      0.55      1533
weighted avg       0.93      0.80      0.85      1533

20.091324200913242


In [11]:
from sklearn.svm import SVC
sv=SVC()                              
sv.fit(X_train,y_train)
y_pred_sv=model.predict(X_test)
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
cm_sv=confusion_matrix(y_test,y_pred_sv)
print(cm_sv)
ac_sv=accuracy_score(y_test,y_pred_sv)
print(ac_sv)
print(classification_report(y_test,y_pred_sv))

from sklearn.metrics import mean_absolute_error
mape_sv = mean_absolute_error(y_test,y_pred_sv)*100
print(mape_sv)

[[1448   10]
 [  72    3]]
0.9465101108936725
              precision    recall  f1-score   support

           0       0.95      0.99      0.97      1458
           1       0.23      0.04      0.07        75

    accuracy                           0.95      1533
   macro avg       0.59      0.52      0.52      1533
weighted avg       0.92      0.95      0.93      1533

5.348988910632746
